stages:

  load_data_stage:
    cmd: python src/stage_01_load_save.py --config=config/config.yaml
    deps:
      - src/stage_01_load_save.py
      - src/utils/all_utils.py
      - config/config.yaml
    outs:
      - artifacts/raw_local_dir/data.csv
  split_data_stage:
    cmd: python src/stage_02_split_data.py --config=config/config.yaml --params=params.yaml
    deps:
      - artifacts/raw_local_dir/data.csv
      - src/stage_02_split_data.py
      - src/utils/all_utils.py
      - config/config.yaml
    params:
      - base.random_state
      - base.test_size
    outs:
      - artifacts/split_data_dir/train.csv
      - artifacts/split_data_dir/test.csv
  training_stage:
    cmd: python src/stage_03_training.py --config=config/config.yaml --params=params.yaml
    deps:
      - src/stage_03_training.py
      - src/utils/all_utils.py
      - config/config.yaml
      - artifacts/split_data_dir/train.csv
      - artifacts/split_data_dir/test.csv
    params:
      - base.random_state
      - Model_params.Elasticnet.alpha
      - Model_params.Elasticnet.l1_ratio
    outs:
      - artifacts/model_dir/Elasticnet.model
  evaluate_stage:
    cmd: python src/stage_04_evaluate.py --config=config/config.yaml
    deps:
      - src/stage_04_evaluate.py
      - src/utils/all_utils.py
      - config/config.yaml
      - artifacts/split_data_dir/test.csv
      - artifacts/model_dir/Elasticnet.model
    outs:
      - artifacts/report_dir/Elasticnet.json
